### ISSUE TITLE
Comentarios guia 4

### ISSUE THREAD

**Issue by GonzaloOBdsol** [WallyMoretti/Java-GuiaObjetos4#1]
**Alquiler.java**

* Le falta un id que identifique al alquiler, puede ser int o UIID
* La fecha devolución en el constructor podes poner this.fechaDevolucion = fechaAlquiler.plusDays(2) y te ahorras de agregarle lógica a esto

**Clasificacion.java**

* Bien el uso de enum

**Cliente.java**

* Bien esta clase

**Genero.java**

* Bien el uso de enum

**Pelicula.java**

* Esta bien esta clase

**VideoStore.java**

* Esta clase no estaría dentro del package de model porque en si contiene lógica. Abórdate que los nombres de los package también va en singular.
* Bien el uso de List
* Bien el manejo de si la lista esta vacía
* Los métodos addPeliculas y addClientes ese contenido estaría instancia en el main y no en estos métodos porque deberían de hacer List.add(Object)

**Main.java**

* Esta parte de los menús no deberías de hacerlo, es muy de C. Acá la idea es crear e instanciar los objetos.
* Solamente deberías de tener los scanner si hace falta y si lo indica el enunciado

**Comment by WallyMoretti** [comment]
Buen dia profe!

Desde ya, le agradezco su corrección y su ayuda y me gustaría hacerle otra
pregunta:
Cuando usted se refiere a que la parte de los menús no debería hacerla, ¿se
refiere al switch que hago? Porque si bien es una costumbre que claramente
vengo arrastrando desde C, lo agregaba para darle como una "forma" por
decirlo de alguna manera.
¿Me conviene entonces hacer los llamados sueltos como vienen en el Main y
ya está?

Desde ya muchas gracias, y que tenga un buen día!

¡Saludos!


Walter Moretti.
